/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nhg;

import org.bukkit.Bukkit;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitScheduler;


public class NHG extends JavaPlugin implements Listener {

    private BukkitScheduler scheduler = Bukkit.getServer().getScheduler();

    private PlayerHandler playerHandler;
    private GameHandler gameHandler;
    private CommandHandler commandHandler;

    @Override
    public void onEnable() {

        gameHandler = new GameHandler(this);
        playerHandler = new PlayerHandler(this);
        commandHandler = new CommandHandler(this);

        Bukkit.getPluginManager().registerEvents(this, this);


        // SCHEDULER //
        scheduler.scheduleSyncRepeatingTask(this, new Runnable() {
            @Override
            public void run() {

                gameHandler.tick();
            }
        }, 0L, 0L);
        
    }

    @Override
    public void onDisable() {

    }

    // EVENTS //

    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent e) {
        playerHandler.joinedPlayer(e.getPlayer());
    }

    @EventHandler
    public void onPlayerLeave(PlayerQuitEvent e) {
        playerHandler.quitPlayer(e.getPlayer());
    }

    public GameHandler getGameHandler() {
        return this.gameHandler;
    }

    public PlayerHandler getPlayerHandler() {
        return this.playerHandler;
    }

}

