/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nhg;

import org.bukkit.plugin.java.JavaPlugin;

public class NHG extends JavaPlugin {
    @Override
    public void onEnable() {

    }

    @Override
    public void onDisable() {

    }
}
